export default {
    theme: {
        extend: {
            colors: {
                'vilt-primary': {
                    50: 'rgb(var(--vilt-primary-50))',
                    100: 'rgb(var(--vilt-primary-100))',
                    200: 'rgb(var(--vilt-primary-200))',
                    300: 'rgb(var(--vilt-primary-300))',
                    400: 'rgb(var(--vilt-primary-400))',
                    500: 'rgb(var(--vilt-primary-500))',
                    600: 'rgb(var(--vilt-primary-600))',
                    700: 'rgb(var(--vilt-primary-700))',
                    800: 'rgb(var(--vilt-primary-800))',
                    900: 'rgb(var(--vilt-primary-900))',
                    950: 'rgb(var(--vilt-primary-950))',
                },
                'vilt-info': {
                    50: 'rgb(var(--vilt-info-50))',
                    100: 'rgb(var(--vilt-info-100))',
                    200: 'rgb(var(--vilt-info-200))',
                    300: 'rgb(var(--vilt-info-300))',
                    400: 'rgb(var(--vilt-info-400))',
                    500: 'rgb(var(--vilt-info-500))',
                    600: 'rgb(var(--vilt-info-600))',
                    700: 'rgb(var(--vilt-info-700))',
                    800: 'rgb(var(--vilt-info-800))',
                    900: 'rgb(var(--vilt-info-900))',
                    950: 'rgb(var(--vilt-info-950))',
                },
                'vilt-success': {
                    50: 'rgb(var(--vilt-success-50))',
                    100: 'rgb(var(--vilt-success-100))',
                    200: 'rgb(var(--vilt-success-200))',
                    300: 'rgb(var(--vilt-success-300))',
                    400: 'rgb(var(--vilt-success-400))',
                    500: 'rgb(var(--vilt-success-500))',
                    600: 'rgb(var(--vilt-success-600))',
                    700: 'rgb(var(--vilt-success-700))',
                    800: 'rgb(var(--vilt-success-800))',
                    900: 'rgb(var(--vilt-success-900))',
                    950: 'rgb(var(--vilt-success-950))',
                },
                'vilt-warning': {
                    50: 'rgb(var(--vilt-warning-50))',
                    100: 'rgb(var(--vilt-warning-100))',
                    200: 'rgb(var(--vilt-warning-200))',
                    300: 'rgb(var(--vilt-warning-300))',
                    400: 'rgb(var(--vilt-warning-400))',
                    500: 'rgb(var(--vilt-warning-500))',
                    600: 'rgb(var(--vilt-warning-600))',
                    700: 'rgb(var(--vilt-warning-700))',
                    800: 'rgb(var(--vilt-warning-800))',
                    900: 'rgb(var(--vilt-warning-900))',
                    950: 'rgb(var(--vilt-warning-950))',
                },
                'vilt-danger': {
                    50: 'rgb(var(--vilt-danger-50))',
                    100: 'rgb(var(--vilt-danger-100))',
                    200: 'rgb(var(--vilt-danger-200))',
                    300: 'rgb(var(--vilt-danger-300))',
                    400: 'rgb(var(--vilt-danger-400))',
                    500: 'rgb(var(--vilt-danger-500))',
                    600: 'rgb(var(--vilt-danger-600))',
                    700: 'rgb(var(--vilt-danger-700))',
                    800: 'rgb(var(--vilt-danger-800))',
                    900: 'rgb(var(--vilt-danger-900))',
                    950: 'rgb(var(--vilt-danger-950))',
                },
                'vilt-custom': {
                    50: 'rgb(var(--vilt-custom-50))',
                    100: 'rgb(var(--vilt-custom-100))',
                    200: 'rgb(var(--vilt-custom-200))',
                    300: 'rgb(var(--vilt-custom-300))',
                    400: 'rgb(var(--vilt-custom-400))',
                    500: 'rgb(var(--vilt-custom-500))',
                    600: 'rgb(var(--vilt-custom-600))',
                    700: 'rgb(var(--vilt-custom-700))',
                    800: 'rgb(var(--vilt-custom-800))',
                    900: 'rgb(var(--vilt-custom-900))',
                    950: 'rgb(var(--vilt-custom-950))',
                },
            },
        },
    },
}
